

from PyQt5 import QtCore, QtGui, QtWidgets
import formCam,formBienPhu,formTraCuu,formHL,formCD,formNguyHiem_CC

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(986, 713)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        MainWindow.setIconSize(QtCore.QSize(40, 40))
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.menu = QtWidgets.QWidget(self.centralwidget)
        self.menu.setGeometry(QtCore.QRect(9, -1, 221, 681))
        self.menu.setObjectName("menu")
        self.menu.setStyleSheet("background-color: #CCCCCC;")
        self.lbAnh = QtWidgets.QLabel(self.menu)
        self.lbAnh.setGeometry(QtCore.QRect(4, 5, 211, 161))
        self.lbAnh.setText("")
        self.lbAnh.setObjectName("lbAnh")
        self.lbAnh.setPixmap(QtGui.QPixmap("../anh/Logo_Bo_Giao_Thong_Van_Tai.png"))
        self.lbAnh.setScaledContents(True)
        self.lbAnh.setAlignment(QtCore.Qt.AlignCenter)
        
        self.bt_BBCam = QtWidgets.QPushButton(self.menu)
        self.bt_BBCam.setGeometry(QtCore.QRect(0, 170, 221, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_BBCam.setFont(font)
        self.bt_BBCam.setObjectName("bt_BBCam")
        self.bt_BBHieuLenh = QtWidgets.QPushButton(self.menu)
        self.bt_BBHieuLenh.setGeometry(QtCore.QRect(0, 210, 221, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_BBHieuLenh.setFont(font)
        self.bt_BBHieuLenh.setObjectName("bt_BBHieuLenh")
        self.bt_BBChiDan = QtWidgets.QPushButton(self.menu)
        self.bt_BBChiDan.setGeometry(QtCore.QRect(0, 250, 221, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_BBChiDan.setFont(font)
        self.bt_BBChiDan.setObjectName("bt_BBChiDan")
        self.bt_BBNguyHiemVaCanhCao = QtWidgets.QPushButton(self.menu)
        self.bt_BBNguyHiemVaCanhCao.setGeometry(QtCore.QRect(0, 290, 221, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_BBNguyHiemVaCanhCao.setFont(font)
        self.bt_BBNguyHiemVaCanhCao.setObjectName("bt_BBNguyHiemVaCanhCao")
        self.bt_BienPhu = QtWidgets.QPushButton(self.menu)
        self.bt_BienPhu.setGeometry(QtCore.QRect(0, 330, 221, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_BienPhu.setFont(font)
        self.bt_BienPhu.setObjectName("bt_BienPhu")
        self.bt_TraCuu = QtWidgets.QPushButton(self.menu)
        self.bt_TraCuu.setGeometry(QtCore.QRect(0, 370, 221, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_TraCuu.setFont(font)
        self.bt_TraCuu.setObjectName("bt_TraCuu")
        self.lb_tieude = QtWidgets.QLabel(self.centralwidget)
        self.lb_tieude.setGeometry(QtCore.QRect(230, 0, 751, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lb_tieude.setFont(font)
        self.lb_tieude.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lb_tieude.setStyleSheet("RGB(173, 216, 230)")
        self.lb_tieude.setObjectName("lb_tieude")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(410, 110, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 150, 611, 51))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 240, 621, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(340, 200, 621, 41))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(340, 290, 621, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(310, 50, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setTabletTracking(False)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(240, 350, 91, 31))
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(340, 350, 631, 31))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(230, 390, 731, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(240, 470, 730, 211))
        self.label_10.setText("") 
        self.label_10.setObjectName("label_10")
        self.label_10.setPixmap(QtGui.QPixmap("../anh/hinhnen.jpg"))
        self.label_10.setScaledContents(True) 
        self.logo_sgu = QtWidgets.QLabel(self.centralwidget)
        self.logo_sgu.setGeometry(QtCore.QRect(240, 40, 55, 41))
        self.logo_sgu.setText("")
        self.logo_sgu.setObjectName("logo_sgu")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 986, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        font_normal = QtGui.QFont()
        font_normal.setPointSize(15)
        font_normal.setBold(False)

        self.label_2.setFont(font_normal)
        self.label_3.setFont(font_normal)
        self.label_4.setFont(font_normal)
        self.label_5.setFont(font_normal)
        font_normal1 = QtGui.QFont()
        font_normal1.setPointSize(13)
        font_normal1.setBold(False)
        self.label_8.setFont(font_normal1)
        self.label_9.setFont(font_normal1)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.bt_BBChiDan.clicked.connect(self.chuyenFormCD)
        self.bt_TraCuu.clicked.connect(self.chuyenFormTraCuu)
        self.bt_BienPhu.clicked.connect(self.chuyenFormBP)
        self.bt_BBCam.clicked.connect(self.chuyenFormCam)
        self.bt_BBHieuLenh.clicked.connect(self.chuyenFormHL)
        self.bt_BBNguyHiemVaCanhCao.clicked.connect(self.chuyenFormNN)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hệ thống quản lí biển báo giao thông"))
        self.bt_BBCam.setText(_translate("MainWindow", "Biển báo cấm"))
        self.bt_BBHieuLenh.setText(_translate("MainWindow", "Biển báo hiệu lệnh"))
        self.bt_BBChiDan.setText(_translate("MainWindow", "Biển báo chỉ dẫn"))
        self.bt_BBNguyHiemVaCanhCao.setText(_translate("MainWindow", "Biển báo nguy hiểm-cảnh báo"))
        self.bt_BienPhu.setText(_translate("MainWindow", "Biển phụ,biển viết bằng chữ"))
        self.bt_TraCuu.setText(_translate("MainWindow", "Tra cứu"))
        self.lb_tieude.setText(_translate("MainWindow", "        Hệ thống quản lí và phân loại biển báo giao thông"))
        self.lb_tieude.setStyleSheet("background-color:#00FFFF")
        self.label.setText(_translate("MainWindow", "Thành viên nhóm HHHV"))
        self.label_2.setText(_translate("MainWindow", "1.Nguyễn Văn Việt       :    3122410469"))
        self.label_3.setText(_translate("MainWindow", "3.Trần Duy Hoàng       :    3122410129"))
        self.label_4.setText(_translate("MainWindow", "2.Vũ Năng Anh Hoàng  :    3122410131"))
        self.label_5.setText(_translate("MainWindow", "4.Trần Hoạt                :    3122410133"))
        self.label_6.setText(_translate("MainWindow", "Trường đại học Sài Gòn"))
        self.logo_sgu.setPixmap(QtGui.QPixmap("../anh/Screenshot 2024-04-16 204844.jpg"))
        self.logo_sgu.setScaledContents(True) 
        self.label_7.setText(_translate("MainWindow", "ĐỀ TÀI :"))
        self.label_8.setText(_translate("MainWindow", "Xây dựng hệ thống quản lí và nhận diện biển báo giao "))
        self.label_9.setText(_translate("MainWindow", " thông bằng hình ảnh ."))
    def chuyenFormCD(self):
        self.form_cd = QtWidgets.QMainWindow()
        self.ui_cd = formCD.Ui_MainWindow()
        self.ui_cd.setupUi(self.form_cd)
        self.form_cd.show()
    def chuyenFormNN(self):
        self.form_nn = QtWidgets.QMainWindow()
        self.ui_nn = formNguyHiem_CC.Ui_MainWindow()
        self.ui_nn.setupUi(self.form_nn)
        self.form_nn.show()
    def chuyenFormCam(self):
        self.form_cam = QtWidgets.QMainWindow()
        self.ui_cam = formCam.Ui_MainWindow()
        self.ui_cam.setupUi(self.form_cam)
        self.form_cam.show()
    def chuyenFormBP(self):
        self.form_bp = QtWidgets.QMainWindow()
        self.ui_bp = formBienPhu.Ui_MainWindow()
        self.ui_bp.setupUi(self.form_bp)
        self.form_bp.show()
    def chuyenFormHL(self):
        self.form_hl = QtWidgets.QMainWindow()
        self.ui_hl = formHL.Ui_MainWindow()
        self.ui_hl.setupUi(self.form_hl)
        self.form_hl.show()
    def chuyenFormTraCuu(self):
        self.form_tc = QtWidgets.QMainWindow()
        self.ui_tc =formTraCuu.Ui_MainWindow()
        self.ui_tc.setupUi(self.form_tc)
        self.form_tc.show()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
